FROM registry.gitlab.com/hcg-openhub/hcg-hub/php:8.1.1-fpm-alpine
WORKDIR /var/www/html
COPY . /var/www/html
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN docker-php-ext-install pdo pdo_mysql



